### ISSUE TITLE
data

### ISSUE THREAD

**Issue by outofstyle** [AlbertiPot/nar#1]
I can't visit Google Drive. Could you share the data on Baidu yun? Thank you very much.

**Comment by AlbertiPot** [comment]
Hi, click here for Baidu [link](https://pan.baidu.com/s/1il2enuZ6OCU6PR_T7p9AgQ), the password is p686. 
If you find the datasets are useful, please star this project and cite the paper.
Thanks :)

**Comment by outofstyle** [comment]
Thanks，I will.
